# How often to poll process list and update their oom_score_adj.
poll_interval = '3s'

# Uppercase rule names are reserved, the DEFAULT is the only one supported now.

# These defaults are used in all rules where not specified explicitly.
[rules.DEFAULT]
# Choomd will only adjust processes owned by the user with id 1000 (default for first non-privileged user).
owner_user_id = [ 1000 ]
# May also filter by user name, but this is less portable as user names differ between systems
#owner_user_name = [ 'futpib' ]

# Rules are applied in order, first match wins.
# String values except for owner_user_name are glob patterns.

# See `rules.rust-analyzer` for a proper way to do this.
# Example match on full path to binary:
#[rules.rust-analyzer-example-full-path]
#command_line_file_path = [ '/home/futpib/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer' ]
#oom_score_adj = 500

# See `rules.rust-analyzer` for a proper way to do this.
# Example glob match on path to binary:
#[rules.rust-analyzer-example-glob]
#command_line_file_path = [ '**/rust-analyzer' ]
#oom_score_adj = 500

[rules.rust-analyzer]
command_line_file_name = [ 'rust-analyzer' ]
oom_score_adj = 500

[rules.node-tsserver-node-modules]
command_line_file_name = [ 'node' ]
command_line_argument = [ '**/tsserver.js' ]
current_working_directory = [ '**/node_modules/**' ]
oom_score_adj = 600

[rules.node-tsserver]
command_line_file_name = [ 'node' ]
command_line_argument = [ '**/tsserver.js' ]
oom_score_adj = 500

[rules.telegram-desktop]
command_line_file_name = [ 'telegram-desktop' ]
oom_score_adj = 500

[rules.firefox-contentproc]
# Plain text explanation:
#   if:
#     - command line filename (without path) is either:
#       - `firefox`
#       - OR `firefox-bin`
#     - AND one of command line arguments is `-contentproc`
#     - AND (from rules.DEFAULT) owner user id is 1000
#   then:
#     - set oom_score_adj to 500
command_line_file_name = [ 'firefox', 'firefox-bin' ]
command_line_argument = [ '-contentproc' ]
oom_score_adj = 500

[rules.firefox]
command_line_file_name = [ 'firefox', 'firefox-bin' ]
oom_score_adj = 450

[rules.chromium-renderer]
command_line_file_name = [ 'chromium', 'chromium-browser', 'chrome', 'chrome-browser' ]
command_line_argument = [ '--type=renderer' ]
oom_score_adj = 500

[rules.chromium]
command_line_file_name = [ 'chromium', 'chromium-browser', 'chrome', 'chrome-browser' ]
oom_score_adj = 450

[rules.emacs]
command_line_file_name = [ 'emacs' ]
oom_score_adj = 400

[rules.xmonad]
command_line_file_name = [ 'xmonad', 'xmonad-x86_64-linux' ]
oom_score_adj = 100
